In [4]:
import sys
sys.path.append("../src/")

In [5]:
%load_ext autoreload
%autoreload 2
import training
from training import ModelRunner

In [8]:
args = """--emsize 768 --nhid 1536 --nlayers 2 --contrasts=16 --emsize 768 --nhid 1536 
--bptt 50 --batch_size 2 --val_data ../data/train/ --restore ../checkpoints/chkpt-1-2000-model.pt"""
runner = ModelRunner(args.split())

In [9]:
runner.evaluate(20)

  1%|          | 21/3039 [00:33<1:20:40,  1.60s/it]


(1.8119939728216692, 0.5254545)

# There is a bug where we reload the model and it's much worse than training

* [x] check that the bert embeddings are the same between different runs and the cluster
* restart training from the checkpoint and check if it's the same
* [x] check the parameters in the model
* add validation to the training run
* try training on cpu for a few cycles and see if it quickly improves

In [28]:
import data
import glob
import torch
from torch.utils.data import DataLoader


In [40]:
val_data_files = glob.glob("../data/test/"+"/"+training.DATANAME_WILDCARD)
valid_dataset = data.HierLMDataset(val_data_files, runner.args.bptt, torch.device('cpu'))
valid_data_loader = DataLoader(valid_dataset, batch_size=runner.args.batch_size,
                                    num_workers=0)

In [41]:
for x in valid_data_loader:
    print(x.shape)
    break

torch.Size([2, 51, 768])


In [39]:
print(x[0,:3,:10])
print(x[1,:3,:10])

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.7935, -0.0909, -1.0857, -0.8614,  1.6374, -0.5583,  0.6060,  0.6450,
          0.2494, -0.1281],
        [-0.2442, -0.1593, -0.7816, -0.8825,  1.7064, -0.3027,  0.2993,  0.6249,
          0.0533, -0.1491]])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.2954,  0.0696,  0.4350,  0.0439,  0.2796,  0.4314,  0.0597,  1.0496,
          0.0784, -0.4132],
        [-0.0771, -0.1494,  0.0512, -0.3159,  0.3643,  0.2208,  0.0433,  0.5378,
         -0.1664, -0.5099]])


In [42]:
print(x[0,:3,:10])
print(x[1,:3,:10])

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.7935, -0.0909, -1.0857, -0.8614,  1.6374, -0.5583,  0.6060,  0.6450,
          0.2494, -0.1281],
        [-0.2442, -0.1593, -0.7816, -0.8825,  1.7064, -0.3027,  0.2993,  0.6249,
          0.0533, -0.1491]])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.2954,  0.0696,  0.4350,  0.0439,  0.2796,  0.4314,  0.0597,  1.0496,
          0.0784, -0.4132],
        [-0.0771, -0.1494,  0.0512, -0.3159,  0.3643,  0.2208,  0.0433,  0.5378,
         -0.1664, -0.5099]])


In [2]:
import torch

In [6]:
with open("../checkpoints/chkpt-1-2000-model.pt", 'rb') as f:
    model = torch.load(f, map_location=torch.device('cpu'))

In [7]:
for name, p in model.named_parameters():
    print(name)

transformer_encoder.layers.0.self_attn.in_proj_weight
transformer_encoder.layers.0.self_attn.in_proj_bias
transformer_encoder.layers.0.self_attn.out_proj.weight
transformer_encoder.layers.0.self_attn.out_proj.bias
transformer_encoder.layers.0.linear1.weight
transformer_encoder.layers.0.linear1.bias
transformer_encoder.layers.0.linear2.weight
transformer_encoder.layers.0.linear2.bias
transformer_encoder.layers.0.norm1.weight
transformer_encoder.layers.0.norm1.bias
transformer_encoder.layers.0.norm2.weight
transformer_encoder.layers.0.norm2.bias
transformer_encoder.layers.1.self_attn.in_proj_weight
transformer_encoder.layers.1.self_attn.in_proj_bias
transformer_encoder.layers.1.self_attn.out_proj.weight
transformer_encoder.layers.1.self_attn.out_proj.bias
transformer_encoder.layers.1.linear1.weight
transformer_encoder.layers.1.linear1.bias
transformer_encoder.layers.1.linear2.weight
transformer_encoder.layers.1.linear2.bias
transformer_encoder.layers.1.norm1.weight
transformer_encoder.la